### ISSUE TITLE
Generic comments

### ISSUE THREAD

**Issue by kkoci** [OpenPress/openpress#1]
Hi

1) Why do You need to offer support on all those database engines? With 1 relational and 1 Non relational would be sufficient, I understand your point, but a software/project/community should have a well defined objective.

2) I ran your app but it only has a "Hello world" example, do You plan to have at least a proper login/logout post/get routes?

I suggest you make this development if You want more collaboration, because it sounds like You don't know Node and just want to learn it, that is awesome, don't get me wrong, but usually, the good help comes with good vision/commitment.

Thank You

**Comment by EmpireWorld** [comment]
Thanks for the issue.
I am a experienced node.js developer.
Now i am working on [OPDoc](https://github.com/OpenPress/opdoc) because we first need a documentation generator.
And then see the answers with numbers:

1. I want to make a large support. (User can install it's own support for example if i need mongo i have to install OpenPress mongo driver)

2. The OpenPress is under development you can see development board on [Trello](https://trello.com/b/9eDarpdE/openpress). (As you message you i need your help in [OPDoc](https://github.com/OpenPress/opdoc))

So you can choose work on which of them, [OPDoc](https://github.com/OpenPress/opdoc) or OpenPress?

please tell me.

Thanks.

I wish all the bests for you.

**Comment by kkoci** [comment]
Hi, Thanks for the answer

Yes, but these drivers, would be the generic ones? No OpenPress specific ORM?

I'll check the Trello board

Cheers

**Comment by EmpireWorld** [comment]
The Drivers are individual modules that not included in the source of OpenPress, they have to install them individually.

All the bests.

**Comment by EmpireWorld** [comment]
I'm closing this issue due to it's long open time.
